// examples/vue/simple/src/App.vue
<script setup lang="ts">
import { useSkeletonSetup } from '@sync-skeleton/vue'
import '@sync-skeleton/core/skeleton.css'
import Card from './components/Card.vue'

useSkeletonSetup()
</script>

<template>
  <div class="container">
    <Card />
    <div class="card2">
      <Card />
    </div>
    <div class="card3">
      <Card />
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.card2 {
  margin-left: 16px;
}

.card3 {
  margin-left: 32px;
}
</style>

// src/App.tsx
import { Card } from "./components/card"
import { useSkeletonSetup } from "./lib/react"
import "./skeleton.css"

function App() {
  useSkeletonSetup();

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      <Card />
      <div style={{ marginLeft: 16 }}> <Card /></div>
      <div style={{ marginLeft: 32 }}><Card /></div>
    </div>
  )
}

export default App
